
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "infynno sports app",
  description: "Generated by create next app 14",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
